language: node_js

node_js:
- '12'

install:
- cd boardgame-ui
- yarn install
- yarn global add firebase-tools

script:
- yarn run build

env:
- CI=false

before_deploy:
- cd ..
- pwd && ls -al . && ls -al boardgame-ui

deploy:
- provider: s3
  access_key_id: AKIAZ44C3UA6ZZOSWAZ2
  secret_access_key:
    secure: USO1+1IM2DFkPu4s5qm9XN837xPiIYMAz6yVZzY5XPVoAeWbAvadcvQR0KIP/pMzdXfsdT76oSvgsa3hW9woj7Xe/+PvRj4kIXx8CotaHLVHOfEsanbS8+n2UN5N6OuGcAdnev/nI5xWkcwAGQiRPHJ0jZLYF+/AHjZ48VJIUDa3hy8bQOPT2lB3Mx1frvXYopClM3CxijQoGYTIIB9Hm4f9YTVZOgD6aCkDHA0mLCEqvToPJ+ytV7stJkjdBtG9rPf39ohazme5SOBlQ+xdkCtbJl4pZbEOFHldpWXIBvL69lwmYCHokO+30L/C5i4ncvolXEmNwhieqGadmhnik1Re3sZNlP20sVuTYTfAygu49Ra2ThuKAx7PXX6pEFrHT6JpzrMOxRuiJIovHacxBb48CvV890zhWq5q++MoiW7NH0ilSzhXc1Q8Slz2F/IXNsWPTIiaUMz43vCuI2JnknajwavttV3kIzXzQdjLs9FjoxwlVl1PhFSmhrSCLsk1GQOiMGuLPdf2rrIAuwuV/kp2QILNU5J0YejpqAt+5oW8Pmn4NIMrRvPQaO9jfjdglyihnCn1Q5pqHPWF4EwRd8ERA5+mw7Kb67LHImTyz9bEeHgRqvn2lDrht6bQ4pOFQiTYsOOu3zq48fL6vDau+J6uSvuixnDTGd/4gh/E4xM=
  bucket: prod.boardgamecomponion.com
  acl: public_read
  region: eu-west-1
  skip_cleanup: true
  local_dir: boardgame-ui/dist
  on:
    branch: master
  
- provider: s3
  access_key_id: AKIAZ44C3UA6ZZOSWAZ2
  secret_access_key:
    secure: USO1+1IM2DFkPu4s5qm9XN837xPiIYMAz6yVZzY5XPVoAeWbAvadcvQR0KIP/pMzdXfsdT76oSvgsa3hW9woj7Xe/+PvRj4kIXx8CotaHLVHOfEsanbS8+n2UN5N6OuGcAdnev/nI5xWkcwAGQiRPHJ0jZLYF+/AHjZ48VJIUDa3hy8bQOPT2lB3Mx1frvXYopClM3CxijQoGYTIIB9Hm4f9YTVZOgD6aCkDHA0mLCEqvToPJ+ytV7stJkjdBtG9rPf39ohazme5SOBlQ+xdkCtbJl4pZbEOFHldpWXIBvL69lwmYCHokO+30L/C5i4ncvolXEmNwhieqGadmhnik1Re3sZNlP20sVuTYTfAygu49Ra2ThuKAx7PXX6pEFrHT6JpzrMOxRuiJIovHacxBb48CvV890zhWq5q++MoiW7NH0ilSzhXc1Q8Slz2F/IXNsWPTIiaUMz43vCuI2JnknajwavttV3kIzXzQdjLs9FjoxwlVl1PhFSmhrSCLsk1GQOiMGuLPdf2rrIAuwuV/kp2QILNU5J0YejpqAt+5oW8Pmn4NIMrRvPQaO9jfjdglyihnCn1Q5pqHPWF4EwRd8ERA5+mw7Kb67LHImTyz9bEeHgRqvn2lDrht6bQ4pOFQiTYsOOu3zq48fL6vDau+J6uSvuixnDTGd/4gh/E4xM=
  bucket: stg.boardgamecomponion.com
  acl: public_read
  region: eu-west-1
  skip_cleanup: true
  local_dir: boardgame-ui/dist
  on:
    branch: develop