language: node_js

node_js:
- '11'

install:
- cd boardgame-ui
- yarn install
- yarn global add firebase-tools

script:
- yarn run build

env:
- CI=false

before_deploy:
- cd ..
- pwd && ls -al

deploy:
- provider: s3
  access_key_id: AKIA3VNF2BITTQFHZ5HJ
  secret_access_key:
    secure: G7YsApintyp3BrfrFC5TiSH5lt/1Q6D46H4Itldn+lNMc2Y0g8k5FzNLvq1QDe3KCYbAE4I1qguzYbVhLupoIvjHEAmVpEDatdB0e8P8Hp9qp5Tp8f41MCbC/Dd6IxO4jMN/MUXe3a7flQnP8Z/hztHXZXo83vGP8Xd41CbaWVnnO/FwvIapHV4tr2F2LHlWrpc+/5M4dhzG0YB2JlD1eDibw1O2ez2NbWvQLqS2sWtdslTc3zDULm0rmSBS2jGB7Dq5Ls0FujyIVsBdD4V4ol9on/IRH/smo1LGhC0kBfrd5RMWoNnhV6ctP26cDR+jo6Jv8V7ZbSHt7yhZm9ndv3IRYZiTmta4LjdXSypOlvwtNBFs11ZXEjj/ldaQpKus2LjM+iK219tCSfjImxSgHWoUthaxVeC8lgStUeJv/s4PQuucTpq7ngdQXla0eRqdlzVAQqA+SSldDfk//ZekNsLtAkPR5tqxNnppVesF5nTsvZyfduAjWsBk1nTPGJCBJe/bkCQzuuGiNJLwKOhdhgCPVsRoe42vvZqPolM4Mue5ov3GYzr01enc+BPYtWDxVhL/zwl3pnE/XH6oZ2IdVE/n5NmFa3XZOKaQwVSHtzwUSuAuIULPwTVrGMcuha9ipXb9zuiyKD9kEx8gXoxuepmTShnUBGyaDRUAoq1Pd44=
  bucket: www.boardgamecomponion.com
  acl: public_read
  region: eu-west-1
  skip_cleanup: true
  local_dir: boardgame-ui/dist
  on:
    branch: master

- provider: firebase
  token:
    secure: "bvpf/ndH2xil7Orl4fa9q5jGkVxY3fSGNVyilHIUA2EIgppe27oxfNCR52lKAf06R33aCfZvDBvPqE+LESvQXqTGYq0wCmdFI15peqZpqhEREZaNOR42KRxfOrUadE/zZ4XtOv5R4oUdbwot7kWZzmVOWmFHX7N8CK0Oh+wyCFAPYs/cV70jtS+JzhQt7fV1eX8jBK2LyStm/z/JPZigv+rjFSuwJ9OxrSDHmE50p1GjaAONZu0VlrP34aDQg6bVVsunBlwijBxg+LBE5XWGMp8yEgHpiSEN/AJeFyk74VH4/yCfTdkmFaL/qRjqF313fVU59AFIa1Bi8zlc3+xhNJ4iH6etQfx1ZsTw/gzgiESQzD41mPnkSm/F4PxssUMPaDAGqBQfeczWy3WV7gWh3rvds3vpxkRF0mvqG4MTxJ+BbrVTfJVtyN2WXgpclDEL7cr3ZzZ5kYmO13mQAKlLmUFbBXKuS130SUsnlie9oLlRS76wySYAyYJ3WIiVeDO5HsDSC54pCJs3GV7RXIduqpf/TvYMYvGv4Pf+2YS5myDBJn+lhEWmRRA7g5VRFVrho7JJxhNG4PiuF9SQuDN1r9wrKcoa8q1Ol9nN2wjoiVZTvrxYnBKOJqsv31mRkQNKF4gBbJ46fjzEALXZzXJ9sJEg9uXWR4EgRjHee9Q3GUM="
  project: boardgameweekend
  skip_cleanup: true
  local_dir: boardgame-ui/dist
  on:
    branch: develop

