language: node_js

node_js:
- '12'

install:
- cd boardgame-ui
- yarn install
- yarn global add firebase-tools

script:
- yarn run build

env:
- CI=false

before_deploy:
- cd ..
- pwd && ls -al . && ls -al boardgame-ui

deploy:
- provider: s3
  access_key_id: AKIAZ44C3UA6ZZOSWAZ2
  secret_access_key:
    secure: UEqC8kw2+44iue6Lgf1XcZhINkYMhRRTdzTjQ4oel10JwlmiKzGv2EZCNysltckiNh5AWB9xkbgD3fI7dbUp+acAeew2vLrMJw2U0mgIJjhWOaFluT1zzDkfsTRGJT/n1YWJ/iaqI9raJnMWB45jEVYghcmmLMX0FVOZ/H47Dp9RDvbfpXvASQbedT5OTzeHyeF8WzYgA4b30Ogw9lZPGpt3uPcfMVmag+jl+wrTKroD5WQxxiagYvBFBGv12lDB9izuaAmW+vshmWELskvzzFbwb9mruX91PcS7c9qp+pRzgGoUdTn/73/2q0UegGvWLQczD5Wtl9cIEZfegSKnp3wY24BEd6N71ownAB5Fdfy8+Sh8jpKIB1B3roYxz3vgBGyCEsz4egGVj0lJHE3xwx2KmOfFOVIB/09nkl1uR1JbSINGxa1s74fdUYwfEz2IMAkFZKoaRioSQVZwV4rtL7Fb8K3M5aJqIHBn2UQjs8413hhFii4EG85hOsVOBRcFlfRoimvyY+pb0ITQ82s/eRNbXmihXZlRGF1DKY3VQet3CjeleeyZMv0Yb7k8kA2ONksSYLz9sijiT2QiQ5vejJXw/sOt8wvj1sxgi7Vbagy5QEcAYYRWYOpK23011MrPlNmSKe4IpiHVDRidBuI3uHKx1I1dNBVxXqiGDOBCYYE=
  bucket: prod.boardgamecomponion.com
  acl: public_read
  region: eu-west-1
  skip_cleanup: true
  local_dir: boardgame-ui/dist
  on:
    branch: master
  
- provider: s3
  access_key_id: AKIAZ44C3UA6ZZOSWAZ2
  secret_access_key:
    secure: UEqC8kw2+44iue6Lgf1XcZhINkYMhRRTdzTjQ4oel10JwlmiKzGv2EZCNysltckiNh5AWB9xkbgD3fI7dbUp+acAeew2vLrMJw2U0mgIJjhWOaFluT1zzDkfsTRGJT/n1YWJ/iaqI9raJnMWB45jEVYghcmmLMX0FVOZ/H47Dp9RDvbfpXvASQbedT5OTzeHyeF8WzYgA4b30Ogw9lZPGpt3uPcfMVmag+jl+wrTKroD5WQxxiagYvBFBGv12lDB9izuaAmW+vshmWELskvzzFbwb9mruX91PcS7c9qp+pRzgGoUdTn/73/2q0UegGvWLQczD5Wtl9cIEZfegSKnp3wY24BEd6N71ownAB5Fdfy8+Sh8jpKIB1B3roYxz3vgBGyCEsz4egGVj0lJHE3xwx2KmOfFOVIB/09nkl1uR1JbSINGxa1s74fdUYwfEz2IMAkFZKoaRioSQVZwV4rtL7Fb8K3M5aJqIHBn2UQjs8413hhFii4EG85hOsVOBRcFlfRoimvyY+pb0ITQ82s/eRNbXmihXZlRGF1DKY3VQet3CjeleeyZMv0Yb7k8kA2ONksSYLz9sijiT2QiQ5vejJXw/sOt8wvj1sxgi7Vbagy5QEcAYYRWYOpK23011MrPlNmSKe4IpiHVDRidBuI3uHKx1I1dNBVxXqiGDOBCYYE=
  bucket: stg.boardgamecomponion.com
  acl: public_read
  region: eu-west-1
  skip_cleanup: true
  local_dir: boardgame-ui/dist
  on:
    branch: develop