language: node_js

node_js:
- '11'

install:
- cd boardgame-ui
- yarn install
- yarn global add firebase-tools

script:
- yarn run build

env:
- CI=false

before_deploy:
- cd ..

deploy:
- provider: firebase
  token:
    secure: "bvpf/ndH2xil7Orl4fa9q5jGkVxY3fSGNVyilHIUA2EIgppe27oxfNCR52lKAf06R33aCfZvDBvPqE+LESvQXqTGYq0wCmdFI15peqZpqhEREZaNOR42KRxfOrUadE/zZ4XtOv5R4oUdbwot7kWZzmVOWmFHX7N8CK0Oh+wyCFAPYs/cV70jtS+JzhQt7fV1eX8jBK2LyStm/z/JPZigv+rjFSuwJ9OxrSDHmE50p1GjaAONZu0VlrP34aDQg6bVVsunBlwijBxg+LBE5XWGMp8yEgHpiSEN/AJeFyk74VH4/yCfTdkmFaL/qRjqF313fVU59AFIa1Bi8zlc3+xhNJ4iH6etQfx1ZsTw/gzgiESQzD41mPnkSm/F4PxssUMPaDAGqBQfeczWy3WV7gWh3rvds3vpxkRF0mvqG4MTxJ+BbrVTfJVtyN2WXgpclDEL7cr3ZzZ5kYmO13mQAKlLmUFbBXKuS130SUsnlie9oLlRS76wySYAyYJ3WIiVeDO5HsDSC54pCJs3GV7RXIduqpf/TvYMYvGv4Pf+2YS5myDBJn+lhEWmRRA7g5VRFVrho7JJxhNG4PiuF9SQuDN1r9wrKcoa8q1Ol9nN2wjoiVZTvrxYnBKOJqsv31mRkQNKF4gBbJ46fjzEALXZzXJ9sJEg9uXWR4EgRjHee9Q3GUM="
  project: boardgameweekend
  skip_cleanup: true
  local_dir: boardgame-ui/dist
  on:
    branch: develop
