version: '3'
services:
  web:
    image: "node:8"
    working_dir: /home/node/app
    restart: always
    expose: 
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ../boardgame-ui:/home/node/app
    command: bash -c "yarn install && yarn serve"
