version: '3'
services:
  web:
    image: "node:8"
    working_dir: /home/node/app
    restart: always
    expose: 
      - "3000"
    ports:
      - "3044:3000"
    volumes:
      - ../boardgamewe-ui:/home/node/app
    command: bash -c "npm install && npm start"
